import type { PrototypeConflict, PrototypeDevice, PrototypeRevision, PrototypeScenario } from './types'

const conflicts: PrototypeConflict[] = [
  {
    id: 'clock-size',
    category: '设置',
    label: '时钟大小',
    local: '64 px',
    remote: '56 px',
    base: '50 px',
    localDevice: 'Chrome · Windows · A7K3',
    remoteDevice: 'Firefox · macOS · M2F8',
    modifiedAt: '今天 14:32 / 今天 14:28',
    canKeepBoth: false,
  },
  {
    id: 'quick-link-docs',
    category: '快速导航',
    label: '“项目文档”快捷方式',
    local: '已删除',
    remote: '标题改为“团队文档”',
    base: '项目文档 · https://docs.example.com',
    localDevice: 'Chrome · Windows · A7K3',
    remoteDevice: 'Firefox · macOS · M2F8',
    modifiedAt: '今天 14:30 / 今天 14:31',
    canKeepBoth: true,
  },
  {
    id: 'quick-link-order',
    category: '快速导航',
    label: '“工作”分组的项目顺序',
    local: '邮箱、日历、文档',
    remote: '文档、邮箱、日历',
    base: '邮箱、文档、日历',
    localDevice: 'Chrome · Windows · A7K3',
    remoteDevice: 'Firefox · macOS · M2F8',
    modifiedAt: '今天 14:33 / 今天 14:29',
    canKeepBoth: false,
  },
]

const history: PrototypeRevision[] = [
  {
    id: 'rev-10',
    time: '今天 14:35',
    device: 'Chrome · Windows · A7K3',
    reason: '自动合并',
    summary: '31 项设置、18 个快速导航、3 个搜索引擎',
    integrity: 'complete',
    wallpaperAvailable: true,
  },
  {
    id: 'rev-9',
    time: '今天 10:12',
    device: 'Firefox · macOS · M2F8',
    reason: '本地修改',
    summary: '30 项设置、18 个快速导航、3 个搜索引擎',
    integrity: 'complete',
    wallpaperAvailable: false,
  },
  {
    id: 'rev-8',
    time: '昨天 22:08',
    device: 'Chrome · Android · P4N6',
    reason: '立即同步',
    summary: '30 项设置、17 个快速导航、3 个搜索引擎',
    integrity: 'complete',
    wallpaperAvailable: false,
  },
]

const corruptedHistory: PrototypeRevision[] = [
  {
    id: 'rev-bad',
    time: '今天 14:35',
    device: 'Firefox · macOS · M2F8',
    reason: '本地修改',
    summary: '正文 SHA-256 与提交记录不一致',
    integrity: 'corrupted',
    wallpaperAvailable: false,
  },
  ...history,
]

const devices: PrototypeDevice[] = [
  {
    id: 'a',
    name: 'Chrome · Windows · A7K3',
    firstSeen: '2026-07-12',
    lastSeen: '刚刚',
    status: 'active',
  },
  {
    id: 'b',
    name: 'Firefox · macOS · M2F8',
    firstSeen: '2026-07-15',
    lastSeen: '2 小时前',
    status: 'active',
  },
  {
    id: 'c',
    name: 'Chrome · Android · P4N6',
    firstSeen: '2025-11-02',
    lastSeen: '190 天前',
    status: 'stale',
  },
]

const base = {
  encrypted: false,
  remoteHasData: true,
  coreSize: '186 KB',
  wallpaper: { count: 2, totalSize: '12.8 MB', lightSize: '7.4 MB', darkSize: '5.4 MB' },
  conflicts: [],
  history,
  devices,
} satisfies Omit<PrototypeScenario, 'id' | 'label' | 'status' | 'statusLabel' | 'summary' | 'detail'>

export const scenarios: readonly PrototypeScenario[] = [
  {
    ...base,
    id: 'unconfigured',
    label: '未配置',
    status: 'unconfigured',
    statusLabel: '尚未设置',
    summary: '在自己的 WebDAV 空间中保存设置和快速导航',
    detail: '首次连接只会扫描远端目录。确认同步范围前不会上传或修改任何数据。',
    remoteHasData: false,
    history: [],
    devices: [],
  },
  {
    ...base,
    id: 'existing-library',
    label: '首次连接已有库',
    status: 'pending',
    statusLabel: '等待首次比较',
    summary: '远端已有来自其他设备的数据',
    detail: '安全部分已经可以合并；需要确认 2 项差异后才能开启同步。',
    pendingChanges: 2,
    conflicts: conflicts.slice(0, 2),
  },
  {
    ...base,
    id: 'synced',
    label: '同步正常',
    status: 'synced',
    statusLabel: '已同步',
    summary: '核心数据与远端一致',
    detail: '壁纸、搜索记录和隐藏站点按当前范围设置处理。',
    lastSuccess: '今天 14:35',
  },
  {
    ...base,
    id: 'auto-merge',
    label: '可自动合并',
    status: 'pending',
    statusLabel: '发现双方修改',
    summary: '修改互不重叠，可以安全自动合并',
    detail: '本机调整了时钟大小，远端新增了一个快速导航；不会覆盖任何一方。',
    pendingChanges: 2,
  },
  {
    ...base,
    id: 'conflict',
    label: '存在冲突',
    status: 'conflict',
    statusLabel: '同步已暂停',
    summary: '有 3 项修改无法安全自动合并',
    detail: '暂停期间不会上传，也不会把云端数据应用到本机。冲突不会自动过期。',
    conflictCount: 3,
    conflicts,
  },
  {
    ...base,
    id: 'permission',
    label: '等待权限',
    status: 'permission',
    statusLabel: '核心数据已同步',
    summary: '2 项功能等待此设备授权',
    detail: 'Monet 取色和网站图标缓存尚未授权；拒绝不会影响其他数据同步。',
    lastSuccess: '今天 14:35',
  },
  {
    ...base,
    id: 'wallpaper-too-large',
    label: '壁纸超限',
    status: 'wallpaper',
    statusLabel: '核心数据已同步',
    summary: '浅色壁纸超过 20 MB，未同步该文件',
    detail: '原图没有被修改。可以预览压缩结果，确认后再替换并上传。',
    lastSuccess: '今天 14:35',
    wallpaper: {
      count: 2,
      totalSize: '29.7 MB',
      lightSize: '24.3 MB',
      darkSize: '5.4 MB',
      tooLarge: true,
    },
  },
  {
    ...base,
    id: 'storage-full',
    label: '空间不足',
    status: 'storage-full',
    statusLabel: '上传已暂停',
    summary: 'WebDAV 空间不足，核心版本也无法保存',
    detail: '可以停止同步壁纸并删除云端壁纸，或把历史数量从 10 调低。',
  },
  {
    ...base,
    id: 'corrupted',
    label: '远端版本损坏',
    status: 'corrupted',
    statusLabel: '同步已暂停',
    summary: '最新版本未通过完整性检查',
    detail: '已停止上传和应用。可以下载原始文件，再与上一份完整版本比较修复。',
    history: corruptedHistory,
  },
  {
    ...base,
    id: 'format-newer',
    label: '格式过新',
    status: 'format-newer',
    statusLabel: '需要升级扩展',
    summary: '此同步库由更新版本的柠檬起始页创建',
    detail: '当前版本无法理解其中的数据，已停止上传和应用，避免覆盖新格式。',
  },
  {
    ...base,
    id: 'encrypted-locked',
    label: '加密库锁定',
    status: 'encrypted-locked',
    statusLabel: '等待加密密码',
    summary: '此同步库已启用客户端加密',
    detail: '请输入独立的同步加密密码。它不是 WebDAV 登录密码，忘记后无法找回。',
    encrypted: true,
  },
] as const
